/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Kroj_Core_Network_SocketBind_ChannelBinder */

#ifndef _Included_org_Kroj_Core_Network_SocketBind_ChannelBinder
#define _Included_org_Kroj_Core_Network_SocketBind_ChannelBinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Kroj_Core_Network_SocketBind_ChannelBinder
 * Method:    bindToDevice
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Kroj_Core_Network_SocketBind_ChannelBinder_bindToDevice
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
