plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.2.2'
    id 'org.graalvm.buildtools.native'
}

group = 'org.kroj'
version = '1.0.0'

ext.targetPlatform = project.hasProperty('targetPlatform') ? project.property('targetPlatform') :
    (System.getProperty('os.name').toLowerCase().contains('win') ? 'windows-x86_64' :
     System.getProperty('os.name').toLowerCase().contains('mac') ? (System.getProperty('os.arch').contains('aarch64') ? 'osx-aarch_64' : 'osx-x86_64') : 'linux-x86_64')

dependencies {
    implementation project(":Core")
    implementation 'io.github.mkpaz:atlantafx-base:2.1.0'

    def jfx = javafx.version
    def jfxOs = targetPlatform.startsWith('win') ? 'win' :
                targetPlatform.startsWith('osx') ? (targetPlatform.contains('aarch64') ? 'mac-aarch64' : 'mac') : 'linux'

    runtimeOnly "org.openjfx:javafx-base:$jfx:$jfxOs"
    runtimeOnly "org.openjfx:javafx-graphics:$jfx:$jfxOs"
    runtimeOnly "org.openjfx:javafx-controls:$jfx:$jfxOs"
    runtimeOnly "org.openjfx:javafx-fxml:$jfx:$jfxOs"
}

javafx {
    version = "21.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.base' ]
}

application {
    mainClass = "org.Kroj.UI.Main"
}

shadowJar {
    archiveFileName = "JVDM-UI.jar"
    mergeServiceFiles()
    exclude "META-INF/*.SF"
    exclude "META-INF/*.DSA"
    exclude "META-INF/*.RSA"
    exclude "META-INF/versions/**/module-info.class"
}

graalvmNative {
    metadataRepository {
        enabled = true
    }
    binaries {
        main {
            imageName = 'JVDM'
            mainClass = application.mainClass.get()
            debug = false
            verbose = false
            fallback = false
            sharedLibrary = false
            quickBuild = false
            richOutput = true
            useFatJar = false

//            buildArgs.add()
            buildArgs.add('-H:+UnlockExperimentalVMOptions')
            buildArgs.add('-H:IncludeResources=.*\\.(fxml|css|png|so|json|properties)')
            buildArgs.add('-H:-ReportExceptionStackTraces')
            buildArgs.add('--gc=serial')
            buildArgs.add('--no-fallback')
            buildArgs.add('--enable-url-protocols=http,https')
            buildArgs.add('-O3')

            buildArgs.add('--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSLPrivateKeyMethod')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.CertificateCompressionAlgo')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSL')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSLContext')
            buildArgs.add('--initialize-at-run-time=org.Kroj.Core.Network.Download.Security.TLS')

            def pgo = file("src/pgo-profiles/main/default.iprof");
            if (pgo.exists()) {
                buildArgs.add("--pgo=${pgo.absolutePath}")
            }

            def currentArch = System.getProperty("os.arch").toLowerCase()

            if (currentArch.contains("aarch64") || currentArch.contains("arm64")) {
                buildArgs.add('-march=armv8-a')
            } else {
                buildArgs.add('-march=x86-64-v3')
            }

            jvmArgs.add('-Dio.netty.tryReflectionSetAccessible=true')
            jvmArgs.add('-Dio.netty.allocator.type=pooled')
            jvmArgs.add('-XX:MaxDirectMemorySize=2G')
            jvmArgs.add('--enable-native-access=ALL-UNNAMED')

            jvmArgs.add('-Dglass.gtk.disableGtk3=true')
            jvmArgs.add('-Dprism.order=d3d,es2,sw')
            jvmArgs.add('-Dprism.vsync=true')
        }
    }

    agent {
        defaultMode = "standard"
        enabled = true

        trackReflectionMetadata = true

        metadataCopy {
            inputTaskNames.add("run")
            outputDirectories.add("src/main/resources/META-INF/native-image/org.kroj/UI/")
            mergeWithExisting = true
        }
    }
}
