import org.gradle.internal.os.OperatingSystem
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.2.2'
    id 'org.graalvm.buildtools.native'
}

group = 'org.kroj'
version = '1.0.0'

def os = OperatingSystem.current();

configurations {
    theWin { transitive = false }
    theLinux { transitive = false }
    theMac { transitive = false }
    theMacArm { transitive = false }
}

dependencies {
    implementation project(":Core")
    implementation 'io.github.mkpaz:atlantafx-base:2.1.0'

    def jfx = '21'

    theWin "org.openjfx:javafx-base:$jfx:win"
    theWin "org.openjfx:javafx-graphics:$jfx:win"
    theWin "org.openjfx:javafx-controls:$jfx:win"
    theWin "org.openjfx:javafx-fxml:$jfx:win"

    theLinux "org.openjfx:javafx-base:$jfx:linux"
    theLinux "org.openjfx:javafx-graphics:$jfx:linux"
    theLinux "org.openjfx:javafx-controls:$jfx:linux"
    theLinux "org.openjfx:javafx-fxml:$jfx:linux"

    theMac "org.openjfx:javafx-base:$jfx:mac"
    theMac "org.openjfx:javafx-graphics:$jfx:mac"
    theMac "org.openjfx:javafx-controls:$jfx:mac"
    theMac "org.openjfx:javafx-fxml:$jfx:mac"

    theMacArm "org.openjfx:javafx-base:$jfx:mac-aarch64"
    theMacArm "org.openjfx:javafx-graphics:$jfx:mac-aarch64"
    theMacArm "org.openjfx:javafx-controls:$jfx:mac-aarch64"
    theMacArm "org.openjfx:javafx-fxml:$jfx:mac-aarch64"
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.base' ]
}

application {
    mainClass = "org.Kroj.UI.Main"
}

shadowJar {
    archiveFileName = "JVDM-UI.jar"

    configurations = [
            project.configurations.runtimeClasspath,
            project.configurations.theWin,
            project.configurations.theLinux,
            project.configurations.theMac,
            project.configurations.theMacArm
    ]
    mergeServiceFiles()

    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    exclude 'META-INF/maven/**'
    exclude 'META-INF/LICENSE*', 'META-INF/NOTICE*'
    exclude '**/*.md', '**/*.txt'
}

graalvmNative {
    metadataRepository {
        enabled = true
    }
    binaries {
        main {
            imageName = 'JVDM'
            mainClass = application.mainClass.get()

            if (!os.isMacOsX()) buildArgs.add('-H:+StripDebugInfo')
            buildArgs.add('-H:GenerateDebugInfo=0')

            // Performance
            buildArgs.add('-O3')
            if (os.isLinux()) buildArgs.add('--gc=G1')
            buildArgs.add('-H:+UnlockExperimentalVMOptions')
            buildArgs.add('-Dio.netty.allocator.type=pooled')
            buildArgs.add('-Dprism.vsync=true')
            buildArgs.add('-R:MaxDirectMemorySize=4G')
            def pgo = file("src/pgo-profiles/main/default.iprof")
            if (pgo.exists()) {
                buildArgs.add("--pgo=${pgo.absolutePath}")
            }

            // Libraries
            buildArgs.add('-H:IncludeResources=.*\\.(fxml|css|png|jpg|jpeg|svg|properties|ttf|otf|ico|icns|so|dll|dylib|frag|vert|glsl|hlsl|cl|bsm|obj)$')
            buildArgs.add('--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSLPrivateKeyMethod')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.CertificateCompressionAlgo')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSL')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSLContext')
            buildArgs.add('--initialize-at-run-time=org.Kroj.Core.Network.Download.Security.TLS')
            buildArgs.add('--initialize-at-run-time=org.Kroj.Core.Network.SocketBind.PanamaBinder')


            // Compatibility
            buildArgs.add('-march=compatibility')
            if (os.isWindows()) {
                buildArgs.add('-H:NativeLinkerOption=/SUBSYSTEM:WINDOWS')
                buildArgs.add('-H:NativeLinkerOption=/ENTRY:mainCRTStartup')
            }

            // Prevent Error/Warning
            buildArgs.add('-Dio.netty.tryReflectionSetAccessible=true')
            buildArgs.add('--enable-url-protocols=http,https')
            buildArgs.add('--enable-native-access=ALL-UNNAMED')

        }
    }

    agent {
        defaultMode = "standard"
        enabled = true
        trackReflectionMetadata = true
    }
}