plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.2.2'
    id 'org.graalvm.buildtools.native'
}

group = 'org.kroj'
version = '1.0.0'

configurations {
    theNative
}

dependencies {
    implementation project(":Core")
    implementation 'io.github.mkpaz:atlantafx-base:2.1.0'

    def jfx = javafx.version
    def OSes = ['win', 'mac', 'mac-aarch64', 'linux']

    OSes.forEach { os ->
        theNative "org.openjfx:javafx-base:$jfx:$os"
        theNative "org.openjfx:javafx-graphics:$jfx:$os"
        theNative "org.openjfx:javafx-controls:$jfx:$os"
        theNative "org.openjfx:javafx-fxml:$jfx:$os"
    }
}

javafx {
    version = "21.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.base' ]
}

application {
    mainClass = "org.Kroj.UI.Main"
}

shadowJar {
    archiveFileName = "JVDM-UI.jar"

    configurations = [
            project.configurations.runtimeClasspath,
            project.configurations.theNative
    ]

    mergeServiceFiles()

    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    exclude 'META-INF/maven/**'
    exclude 'META-INF/LICENSE*', 'META-INF/NOTICE*'
    exclude '**/*.md', '**/*.txt'
}

graalvmNative {
    metadataRepository {
        enabled = true
    }
    binaries {
        main {
            imageName = 'JVDM'
            mainClass = application.mainClass.get()
            debug = false
            verbose = true
            fallback = false
            sharedLibrary = false
            quickBuild = false
            richOutput = true
            useFatJar = false

            buildArgs.add('-O3')
            buildArgs.add('-H:+StripDebugInfo')
            buildArgs.add('-H:GenerateDebugInfo=0')
            buildArgs.add('-H:+UnlockExperimentalVMOptions')

            buildArgs.add('-H:IncludeResources=.*\\.(fxml|css|png|jpg|jpeg|svg|properties|ttf|otf|ico|icns|so|dll|dylib|frag|vert|glsl|hlsl|cl|bsm)$') // Not Completed Yet
            buildArgs.add('--enable-url-protocols=http,https')
            buildArgs.add('--enable-native-access=ALL-UNNAMED')

            buildArgs.add('--initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSLPrivateKeyMethod')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.CertificateCompressionAlgo')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSL')
            buildArgs.add('--initialize-at-run-time=io.netty.internal.tcnative.SSLContext')
            buildArgs.add('--initialize-at-run-time=org.Kroj.Core.Network.Download.Security.TLS')
            buildArgs.add('--initialize-at-run-time=org.Kroj.Core.Network.SocketBind.PanamaBinder')

            def pgo = file("src/pgo-profiles/main/default.iprof")
            if (pgo.exists()) {
                buildArgs.add("--pgo=${pgo.absolutePath}")
            }

            def currentArch = System.getProperty("os.arch").toLowerCase()
            if (currentArch.contains("aarch64") || currentArch.contains("arm64")) {
                buildArgs.add('-march=armv8-a')
            } else {
                buildArgs.add('-march=x86-64-v3')
            }

            buildArgs.add('-Dio.netty.tryReflectionSetAccessible=true')
            buildArgs.add('-Dio.netty.allocator.type=pooled')
            buildArgs.add('--enable-native-access=ALL-UNNAMED')
            buildArgs.add('-Dglass.gtk.disableGtk3=true')
            buildArgs.add('-Dprism.order=d3d,es2,sw')
            buildArgs.add('-Dprism.vsync=true')

            jvmArgs.add('-XX:MaxDirectMemorySize=2G')

        }
    }

    agent {
        defaultMode = "standard"
        enabled = true
        trackReflectionMetadata = true
    }
}