name: Build and Release Native Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Oracle GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          native-image-job-reports: 'true'

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libxxf86vm-dev libgl1-mesa-dev libgtk-3-dev libglu1-mesa-dev

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        if: matrix.os != 'windows-latest'
        run: chmod +x gradlew

      - name: Build Native Binary
        run: ./gradlew nativeCompile

      - name: Package Binary
        shell: bash
        run: |
          cd build/native/nativeCompile
          
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            JAR_PATH=$(find ~/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/ -name "*win.jar" | head -n 1)
            if [ -f "$JAR_PATH" ]; then
              echo "فایل بومی پیدا شد: $JAR_PATH"
              unzip -o -j "$JAR_PATH" "*.dll" -d .
            else
              echo "Native JAVAFX File Not Found!"
            fi
          
            powershell Compress-Archive -Path jvdm.exe, *.dll -DestinationPath ../../../jvdm-windows.zip
          
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r ../../../jvdm-macos.zip jvdm
          else
            zip -r ../../../jvdm-linux.zip jvdm
          fi

      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            jvdm-windows.zip
            jvdm-macos.zip
            jvdm-linux.zip
